# Generated by Django 4.2.2 on 2023-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_shoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping',
            name='author_name',
            field=models.FileField(null=True, upload_to='', verbose_name='سفارش دهنده'),
        ),
        migrations.AlterField(
            model_name='shoping',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان سفارش'),
        ),
    ]
