# Generated by Django 4.2.2 on 2023-06-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_shoping_author_name_alter_shoping_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoping',
            old_name='title',
            new_name='title_name',
        ),
    ]
