# Generated by Django 4.2.2 on 2023-06-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_rename_title_shoping_title_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام سفارش دهنده')),
            ],
        ),
        migrations.DeleteModel(
            name='Shoping',
        ),
    ]
