# Generated by Django 4.2.7 on 2023-11-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_shaping_delete_shoping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shaping',
        ),
    ]
